-- Create Print Options Table (e.g. 4+4, 1+0)
CREATE TABLE IF NOT EXISTS public.print_options (
    id bigint generated by default as identity primary key,
    print_option text not null, -- '4+4', '1+0', etc.
    price numeric not null, -- Price per sheet (e.g. 15.00)
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Works Table (e.g. Lamination, Cutting)
CREATE TABLE IF NOT EXISTS public.works (
    id bigint generated by default as identity primary key,
    operation text not null, -- 'Blizgi laminacija', 'Pjovimas'
    price numeric not null, -- Price per unit or sheet
    unit text default 'unit', -- 'unit' or 'sheet'
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed Default Data (Based on user docs)
INSERT INTO public.print_options (print_option, price)
SELECT '4+4', 15.00 WHERE NOT EXISTS (SELECT 1 FROM public.print_options WHERE print_option = '4+4');
INSERT INTO public.print_options (print_option, price)
SELECT '4+0', 10.00 WHERE NOT EXISTS (SELECT 1 FROM public.print_options WHERE print_option = '4+0');
INSERT INTO public.print_options (print_option, price)
SELECT '1+1', 7.50 WHERE NOT EXISTS (SELECT 1 FROM public.print_options WHERE print_option = '1+1');
INSERT INTO public.print_options (print_option, price)
SELECT '1+0', 5.00 WHERE NOT EXISTS (SELECT 1 FROM public.print_options WHERE print_option = '1+0');

INSERT INTO public.works (operation, price, unit)
SELECT 'Blizgi laminacija', 2.50, 'unit' WHERE NOT EXISTS (SELECT 1 FROM public.works WHERE operation = 'Blizgi laminacija');
INSERT INTO public.works (operation, price, unit)
SELECT 'Matinė laminacija', 2.00, 'unit' WHERE NOT EXISTS (SELECT 1 FROM public.works WHERE operation = 'Matinė laminacija');

-- Enable RLS
ALTER TABLE public.print_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for all users" ON public.print_options FOR SELECT USING (true);
CREATE POLICY "Enable read for all users" ON public.works FOR SELECT USING (true);
