-- Create Saskaita123 Configuration Table
CREATE TABLE IF NOT EXISTS public."SASKAITA123Data" (
    id bigint generated by default as identity primary key,
    "bankId" text,
    "vatId" text,
    "companyVatId" text, -- Company VAT ID in Saskaita123
    "seriesId" text,
    "unitId" text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Initialize default config (Placeholder)
INSERT INTO public."SASKAITA123Data" (id, "bankId", "vatId", "companyVatId", "seriesId", "unitId")
SELECT 1, 'rkv0294p5enz', '2d9e3v26r04z', '2d9e3v26r04z', '1vre6dkb5enk', 'grn011jm90k5'
WHERE NOT EXISTS (SELECT 1 FROM public."SASKAITA123Data" WHERE id = 1);

-- Create Product-Material Link Table (BOM - many-to-many with quantity)
CREATE TABLE IF NOT EXISTS public.product_materials (
    id bigint generated by default as identity primary key,
    product_id uuid references public.products(id) on delete cascade not null,
    material_id uuid references public.materials(id) on delete cascade not null,
    quantity_per_unit numeric not null default 1, -- How much material per 1 unit of product
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Material Usage Transaction Log
CREATE TABLE IF NOT EXISTS public.material_usage_transactions (
    id bigint generated by default as identity primary key,
    material_id uuid references public.materials(id) on delete set null,
    order_id uuid references public.orders(id) on delete set null,
    order_item_id bigint references public.order_items(id) on delete set null, -- Assuming order_items has BigInt ID
    quantity_used numeric not null,
    transaction_type text not null, -- 'invoiced', 'adjustment', 'waste'
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
ALTER TABLE public."SASKAITA123Data" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_usage_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for authenticated users" ON public."SASKAITA123Data" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.product_materials FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.material_usage_transactions FOR ALL TO authenticated USING (true);
