-- Add missing columns to orders table
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS pack_number text;

-- Create Venipak Pickup Points table (for 800+ lockers)
CREATE TABLE IF NOT EXISTS public.venipak_pickup_points (
    id bigint generated by default as identity primary key,
    pastomat_id text,
    name text,
    pastomat_city text,
    pastomat_address text,
    pastomat_name text,
    pastomat_zip text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Sequence Table for Daily Labels
CREATE TABLE IF NOT EXISTS public.venipak_label_sequences (
    id bigint generated by default as identity primary key,
    label_date date not null,
    sequence_number integer not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Global Sequence Table (Single Row)
CREATE TABLE IF NOT EXISTS public.venipak_global_sequence (
    id bigint generated by default as identity primary key,
    current_sequence bigint not null default 0,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Initialize Global Sequence if empty
INSERT INTO public.venipak_global_sequence (id, current_sequence)
SELECT 1, 9500000
WHERE NOT EXISTS (SELECT 1 FROM public.venipak_global_sequence WHERE id = 1);

-- RLS Policies (Enable Read for All Authenticated Users)
ALTER TABLE public.venipak_pickup_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venipak_label_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venipak_global_sequence ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for authenticated users" ON public.venipak_pickup_points FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users" ON public.venipak_label_sequences FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users" ON public.venipak_global_sequence FOR SELECT TO authenticated USING (true);
